export const GET_BOOTCAMPS_REQUEST = "GET_BOOTCAMPS_REQUEST";
export const GET_BOOTCAMPS_SUCCESS = "GET_BOOTCAMPS_SUCCESS";
export const GET_BOOTCAMPS_FAIL = "GET_BOOTCAMPS_FAIL";

export const GET_BOOTCAMPS_RADIUS_REQUEST = "GET_BOOTCAMPS_RADIUS_REQUEST";
export const GET_BOOTCAMPS_RADIUS_SUCCESS = "GET_BOOTCAMPS_RADIUS_SUCCESS";
export const GET_BOOTCAMPS_RADIUS_FAIL = "GET_BOOTCAMPS_RADIUS_FAIL";
export const GET_BOOTCAMP_RADIUS_RESET = "GET_BOOTCAMP_RADIUS_RESET";

export const GET_BOOTCAMP_REQUEST = "GET_BOOTCAMP_REQUEST";
export const GET_BOOTCAMP_SUCCESS = "GET_BOOTCAMP_SUCCESS";
export const GET_BOOTCAMP_FAIL = "GET_BOOTCAMP_FAIL";
export const GET_BOOTCAMP_RESET = "GET_BOOTCAMP_RESET";

export const GET_BOOTCAMP_COURSE_REQUEST = "GET_BOOTCAMP_COURSE_REQUEST";
export const GET_BOOTCAMP_COURSE_SUCCESS = "GET_BOOTCAMP_COURSE_SUCCESS";
export const GET_BOOTCAMP_COURSE_FAIL = "GET_BOOTCAMP_COURSE_FAIL";
export const GET_BOOTCAMP_COURSE_RESET = "GET_BOOTCAMP_COURSE_RESET";

export const GET_BOOTCAMP_REVIEW_REQUEST = "GET_BOOTCAMP_REVIEW_REQUEST";
export const GET_BOOTCAMP_REVIEW_SUCCESS = "GET_BOOTCAMP_REVIEW_SUCCESS";
export const GET_BOOTCAMP_REVIEW_FAIL = "GET_BOOTCAMP_REVIEW_FAIL";
export const GET_BOOTCAMP_REVIEW_RESET = "GET_BOOTCAMP_REVIEW_RESET";

export const GET_MY_BOOTCAMP_REQUEST = "GET_MY_BOOTCAMP_REQUEST";
export const GET_MY_BOOTCAMP_SUCCESS = "GET_MY_BOOTCAMP_SUCCESS";
export const GET_MY_BOOTCAMP_FAIL = "GET_MY_BOOTCAMP_FAIL";
export const GET_MY_BOOTCAMP_RESET = "GET_MY_BOOTCAMP_RESET";

export const BOOTCAMP_DETAILS_REQUEST = "BOOTCAMP_DETAILS_REQUEST";
export const BOOTCAMP_DETAILS_SUCCESS = "BOOTCAMP_DETAILS_SUCCESS";
export const BOOTCAMP_DETAILS_FAIL = "BOOTCAMP_DETAILS_FAIL";

export const BOOTCAMP_DELETE_REQUEST = "BOOTCAMP_DELETE_REQUEST";
export const BOOTCAMP_DELETE_SUCCESS = "BOOTCAMP_DELETE_SUCCESS";
export const BOOTCAMP_DELETE_FAIL = "BOOTCAMP_DELETE_FAIL";

export const BOOTCAMP_CREATE_REQUEST = "BOOTCAMP_CREATE_REQUEST";
export const BOOTCAMP_CREATE_SUCCESS = "BOOTCAMP_CREATE_SUCCESS";
export const BOOTCAMP_CREATE_FAIL = "BOOTCAMP_CREATE_FAIL";
export const BOOTCAMP_CREATE_RESET = "BOOTCAMP_CREATE_RESET";

export const BOOTCAMP_UPDATE_REQUEST = "BOOTCAMP_UPDATE_REQUEST";
export const BOOTCAMP_UPDATE_SUCCESS = "BOOTCAMP_UPDATE_SUCCESS";
export const BOOTCAMP_UPDATE_FAIL = "BOOTCAMP_UPDATE_FAIL";
export const BOOTCAMP_UPDATE_RESET = "BOOTCAMP_UPDATE_RESET";

export const UPLOAD_BOOTCAMP_COVER_REQUEST = "UPLOAD_BOOTCAMP_COVER_REQUEST";
export const UPLOAD_BOOTCAMP_COVER_SUCCESS = "UPLOAD_BOOTCAMP_COVER_SUCCESS";
export const UPLOAD_BOOTCAMP_COVER_FAIL = "UPLOAD_BOOTCAMP_COVER_FAIL";
export const UPLOAD_BOOTCAMP_COVER_RESET = "UPLOAD_BOOTCAMP_COVER_RESET";
