export const GET_REVIEW_REQUEST = "GET_REVIEW_REQUEST";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_FAIL = "GET_REVIEW_FAIL";

export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAIL = "GET_REVIEWS_FAIL";

export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";
export const REVIEW_CREATE_RESET = "REVIEW_CREATE_RESET";

export const REVIEW_UPDATE_REQUEST = "REVIEW_UPDATE_REQUEST";
export const REVIEW_UPDATE_SUCCESS = "REVIEW_UPDATE_SUCCESS";
export const REVIEW_UPDATE_FAIL = "REVIEW_UPDATE_FAIL";
export const REVIEW_UPDATE_RESET = "REVIEW_UPDATE_RESET";

export const REVIEWS_DELETE_REQUEST = "REVIEWS_DELETE_REQUEST";
export const REVIEWS_DELETE_SUCCESS = "REVIEWS_DELETE_SUCCESS";
export const REVIEWS_DELETE_FAIL = "REVIEWS_DELETE_FAIL";
